2024-10-26 17:24:43,229 - ERROR - get_sensor_data - An error occurred: HTTPConnectionPool(host='192.168.68.134', port=80): Max retries exceeded with url: /sensor (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020f48087c10>, 'Connection to 192.168.68.134 timed out. (connect timeout=None)'))
2024-10-26 17:25:07,271 - ERROR - get_sensor_data - An error occurred: HTTPConnectionPool(host='192.168.68.134', port=80): Max retries exceeded with url: /sensor (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020f486a9010>, 'Connection to 192.168.68.134 timed out. (connect timeout=None)'))
